### ISSUE TITLE
Question: Can you add multiples homes and the /Back ?

### ISSUE THREAD

**Issue by AndRo-Marian** [DownThePark/SetHome#1]
1. I like it and i say if you can add multiple homes and the /Back.
2. Strange that i don't see the confirmation messages when use /sethome. (Was only for first time. But need to restart the server again to show the messages)

Have 1.14.2
Thanks.

**Comment by SrBedrock** [comment]
Option to set multiple homes would be great!

**Comment by blackcat-917** [comment]
Any updates on this?

**Comment by DownThePark** [comment]
Heya fellas,

Firstly, apologies for the ultra-late response.

Alright so, I don't intend on adding multiple home support to this plugin (at the moment, at least).

As for /back, that feature seems more suited towards a permission-based set-home plugin, which this plugin isn't, so I won't be adding that either.

DownThePark
