### ISSUE TITLE
Cooldown for sethome command

### ISSUE THREAD

**Issue by carlinitos** [DownThePark/SetHome#5]
I've gone through the code and there appears to be a variable for "sethome-command-delay"  But can't be setup in the config file. Would be nice to be able to set a cooldown for players to use sethome just like home-command-delay

**Comment by DownThePark** [comment]
Hello, [carlinitos](https://github.com/carlinitos)

Cooldown support is now fully supported in the latest SetHome release (v6 as of writing).

Thanks,
DownThePark
